### PR TITLE
WIP: chore(typescript): add TypeScript typings

### LINKED ISSUE #12: Cypress-testing-library with typescript
Cypress-testing-library not working with typescript.

### PR DESCRIPTION
**Pull request by aaronmcadam**
**What**: Attempts to fix #12. I've only added support for `getByTestId` to ensure that I've done things correctly. I wonder if there's an easy way to keep up to date with `dom-testing-library`?

**Why**: For TypeScript support

**How**: Added a `typings` directory and added a reference to `package.json`.

I've tried to copy how cypress adds its own types for chainable methods and custom commands: https://github.com/cypress-io/add-cypress-custom-command-in-typescript/blob/master/README.md

**Checklist**:

* [ ] Documentation: add instructions on adding the library types to tsconfig.json
* [ ] Tests
* [ ] Ready to be merged 
* [ ] Added myself to contributors table

### CODE REVIEW

**Comment by sompylasar** [comment]
> I've heard about a way to test typings

Please let me know when you find the way, I'd like to learn it for general awareness.

**Comment by aaronmcadam** [comment]
I think it's worth reaching out to @kentcdodds, as I don't want to add to his already busy workload for a workflow that he doesn't use day to day. My twitter is @aaromcadam @sompylasar if you want to pick things up in the morning (I'm UTC time)

**Comment by aaronmcadam** [comment]
@sompylasar Here's an intro to [type testing with dtslint](https://koerbitz.me/posts/unit-testing-typescript-types-with-dtslint.html)

File: typings/index.d.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+// TypeScript Version: 2.8
+import {
+  SelectorMatcherOptions,
+  Matcher,
+  MatcherOptions,
+  getByTestId,
+} from 'dom-testing-library'
+
+export namespace Cypress {
+  type GetByAttribute = (id: Matcher, options?: MatcherOptions) => Chainable
```
Comment (aaronmcadam) [inline typings/index.d.ts]: I've attempted to copy the implementation here: https://github.com/kentcdodds/dom-testing-library/blob/master/typings/queries.d.ts

**Comment by aaronmcadam** [comment]
Hi @sompylasar, could you give this another look when you get a chance? Thanks!

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by aaronmcadam** [comment]
Do we have any active TypeScript users? These definitions aren't being picked up by VSCode for me.

**Comment by sebastian-ludwig** [comment]
Hi @aaronmcadam, you should probably use global augmentation instead

```typescript
declare global {
  namespace Cypress {
    ...
  }
}
```
